- name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:           ${{ secrets.FTP_HOST }}
          username:         ${{ secrets.FTP_USER }}
          password:         ${{ secrets.FTP_PASSWORD }}
          server-dir:       ${{ secrets.SERVER_PATH }}
          protocol:         ftp
          port:             21
          # ACTIVAMOS ESTO TEMPORALMENTE
          dangerous-clean-slate: true 
          # Mantenemos clean en true
          clean: true
          exclude: |
            **/.git*/**
            **/node_modules/**
            **/vendor/**
            **/storage/framework/cache/**
            **/storage/framework/sessions/**
            **/storage/framework/views/**
            **/storage/logs/**
            **/.env*
            **/tests/**
            **/phpunit.xml*
            **/.phpunit*
            **/README*
            **/*.md